<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6c0bawa\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6c0bawa/appProdProjectContainer.php') {
    touch(__DIR__.'/Container6c0bawa.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container6c0bawa\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container6c0bawa\appProdProjectContainer([
    'container.build_hash' => '6c0bawa',
    'container.build_id' => 'f717353f',
    'container.build_time' => 1574630735,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6c0bawa');
