<?php

namespace Mahmoud\EventBundle\Repository;

/**
 * AcountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcountRepository extends \Doctrine\ORM\EntityRepository
{
}
