<?php

namespace TicketBundle\Repository;

/**
 * ReacteAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReacteAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
