<?php

namespace TicketBundle\Repository;

/**
 * ReactAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReactAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
