<?php

namespace AskBundle\Repository;

/**
 * AskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AskRepository extends \Doctrine\ORM\EntityRepository
{
    public function countab()
    {{ $monfichier9 = fopen('C:\wamp64\www\ChickClickWeb\src\AskBundle\Resources\views\ask\userid.txt', 'r+');
        $userid = fgets($monfichier9);
        fclose($monfichier9);
        $monfichier19 = fopen('C:\wamp64\www\ChickClickWeb\src\AskBundle\Resources\views\ask\visitedid.txt', 'r+');
        $visitedid = fgets($monfichier19);
        fclose($monfichier19);
        $qb=$this->getEntityManager()
    ->createQuery("SELECT COUNT(c.id) FROM FollowBundle:Follower c where c.userId = :dom and c.folowedId = :idom")
        ->setParameters(array('dom' => $userid,'idom' => $visitedid));
    return $result=$qb->getSingleScalarResult();

    }}
    public function supprimer1()
    {$monfichier9 = fopen('C:\wamp64\www\ChickClickWeb\src\AskBundle\Resources\views\ask\userid.txt', 'r+');
        $userid = fgets($monfichier9);
        fclose($monfichier9);
        $monfichier19 = fopen('C:\wamp64\www\ChickClickWeb\src\AskBundle\Resources\views\ask\visitedid.txt', 'r+');
        $visitedid = fgets($monfichier19);
        fclose($monfichier19);
        $qb=$this->getEntityManager()
        ->createQuery("delete FollowBundle:Follower c where c.userId = :dom and c.folowedId = :idom")
        ->setParameters(array('dom'=>$userid,'idom'=>$visitedid))
        ->execute();

    }
    public function recherche($msg,$msg1)
    {{$monfichier19 = fopen('C:\wamp64\www\ChickClickWeb\src\AskBundle\Resources\views\ask\visitedid.txt', 'r+');
        $visitedid = fgets($monfichier19);
        fclose($monfichier19);
        $qb=$this->getEntityManager()
        ->createQuery("Update AskBundle:Ask c SET c.messageDetails = :dom where c.messageDetails = :idom and c.askedId = :iidom")
        ->setParameters(array('dom'=> $msg1,'idom'=> $msg,'iidom'=> $visitedid))
        ->execute();
    }}
    public function supprimer2($msg)
    {$monfichier19 = fopen('C:\wamp64\www\ChickClickWeb\src\AskBundle\Resources\views\ask\visitedid.txt', 'r+');
        $visitedid = fgets($monfichier19);
        fclose($monfichier19);
        $qb=$this->getEntityManager()
        ->createQuery("delete AskBundle:Ask c where c.messageDetails = :idom and c.askedId = :iidom")
        ->setParameters(array('idom'=> $msg,'iidom'=> $visitedid))
        ->execute();

    }
    public function countab1()
    {{ $monfichier11 = fopen('C:\wamp64\www\ChickClickWeb\src\AskBundle\Resources\views\ask\visitedid.txt', 'r+');
        $l = fgets($monfichier11);
        fclose($monfichier11);
        $qb=$this->getEntityManager()
        ->createQuery("SELECT COUNT(c.id) FROM AskBundle:Block c where c.userId = :dom")
        ->setParameter('dom',$l);
        return $result=$qb->getSingleScalarResult();
        }}
    public function supprimer3($msg)
    {$qb=$this->getEntityManager()
        ->createQuery("delete AskBundle:Block c where c.userId = :idom ")
        ->setParameter('idom',$msg)
        ->execute();}
    public function supprimerfolowmobile($userid,$visitedid)
    {

        $qb=$this->getEntityManager()
            ->createQuery("delete FollowBundle:Follower c where c.userId = :dom and c.folowedId = :idom")
            ->setParameters(array('dom'=>$userid,'idom'=>$visitedid))
            ->execute();

    }
    public function veriffolowmobile($userid,$visitedid)
    {{
        $qb=$this->getEntityManager()
            ->createQuery("SELECT COUNT(c.id) FROM FollowBundle:Follower c where c.userId = :dom and c.folowedId = :idom")
            ->setParameters(array('dom' => $userid,'idom' => $visitedid));
        return $result=$qb->getSingleScalarResult();

    }}






}
