<?php

namespace FollowBundle\Repository;

/**
 * FollowerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowerRepository extends \Doctrine\ORM\EntityRepository
{
    public function supprimer()
    {$monfichier19 = fopen('C:\wamp64\www\ChickClickWeb\src\AskBundle\Resources\views\ask\visitedid.txtt', 'r+');
        $visitedid = fgets($monfichier19);
        fclose($monfichier19);
        $monfichier18 = fopen('C:\wamp64\www\ChickClickWeb\src\AskBundle\Resources\views\ask\userid.txt', 'r+');
        $user = fgets($monfichier18);
        fclose($monfichier18);
        $qb=$this->getEntityManager()
        ->createQuery("delete FollowBundle:Follower c where c.userId = :dom and c.folowedId = :idom")
        ->setParameter(array('dom' =>$user,'idom' => $visitedid ))
        ->execute();

    }
}
