<?php

namespace ProductBundle\Repository {

    /**
     * ProductcategoryRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class ProductcategoryRepository extends \Doctrine\ORM\EntityRepository
    {

        public function findByProductcategoryId($id)
        {
            $query =$this->createQueryBuilder('c')
                ->innerJoin('c.productcatid','p')
                ->where('p.productcatid =:id ')
                ->setParameters(array(
                    'id'=>$id
                ))
                ->getQuery();
            return $query->getOneOrNullResult();
        }

    }


}
