<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWnhpznb\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWnhpznb/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWnhpznb.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWnhpznb\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWnhpznb\appDevDebugProjectContainer([
    'container.build_hash' => 'Wnhpznb',
    'container.build_id' => 'ac9b4899',
    'container.build_time' => 1579111515,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWnhpznb');
